[package]
name = "kissabot"
version = "0.1.0"
edition = "2021"

[dependencies]
ctrlc = "3.4.4"
kissa-topic = { path = "kissa-topic" }
kissa-satori = { path = "kissa-satori" }

[workspace]
members = [ "examples/kissa-plugin-example","kissa-satori", "kissa-topic"]
