[package]
name = "kissa-plugin-example"
version = "0.1.0"
edition = "2021"

[dependencies]
kissabot = { path = "../../" }
serde = { version = "1.0.201", features = ["derive"] }

[lib]
crate-type = ["dylib"]
